Todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("home/",include("todos.urls",namespace="todos")),
]

accounts/urls.py
from django.urls import path,include
from . views import login_user,signup_user,logout_user

app_name="accounts"
urlpatterns=[
    path("login/",login_user,name="login"),
    path("signup/",signup_user,name="signup"),
    path("logout/",logout_user,name="logout"),

]

todos/urls.py
from django.urls import path
from . views import index,add_todo,edit,delete,completes,compltete_one,delete_all

app_name="todos"

urlpatterns=[
    path("",index,name="home"),
    path("add/",add_todo,name="add"),
    path("completed/",compltete_one,name="completeone"),
    path("delete-all/",delete_all,name="completedelete"),
    path("edits/<pk>/",edit,name="edt"),
    path("delete-data/<pk>/",delete,name="delte"),
    path("complete-data/<pk>/",completes,name="complete"),
    
]

accounts/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse


class Task(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    complete=models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    #fetching a data through primary key
    def get_absolute_url(self):
        return reverse("todos:edt",kwargs={"pk":self.pk})
    #deleting a data through primary key
    def delete_data(self):
        return reverse("todos:delte",kwargs={"pk":self.pk})

accounts/forms.py
from django.contrib.auth import authenticate,get_user_model
from django import forms

#Fetch model
User=get_user_model()


#Customize Login Form
class UserLogin(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput())
    
    #Overwrite the clean method
    def clean(self,*args,**kwargs):
        username=self.cleaned_data.get("username")
        password=self.cleaned_data.get("password")
        user=authenticate(username=username,password=password)
        if username and password:
            user=authenticate(username=username,password=password)
            if not user:
                raise forms.ValidationError("please enter valid username and password")
            if not user.check_password(password):
                raise forms.ValidationError("please enter valid password")
            if not user.is_active:
                raise forms.ValidationError("user is not active user")
        return super().clean(*args,**kwargs)

#Customize SignUp Form
class UserSignUp(forms.ModelForm):
    email=forms.EmailField(label="Email")
    email2=forms.EmailField(label="Email")
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=("username","email","email2","password")
   
    def clean(self,*args,**kwargs):
        email=self.cleaned_data.get("email")
        email2=self.cleaned_data.get("email2")
        if email!=email2:
            raise forms.ValidationError("please enter same email for both email fields")
        email_qs=User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return super().clean(*args,**kwargs)

todos/forms.py
from django import forms
from . models import Task

class TaskForm(forms.ModelForm):

    class Meta:
        model=Task
        fields=("title",)
        widgets={"title":forms.TextInput(attrs={"type":"text","class":"form-control","id":"title","placeholder":"please add your wish"})}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout,get_user_model
from . forms import UserLogin,UserSignUp
from django.contrib import messages

#method used for custom login
def login_user(request):
    nexts=request.GET.get("next")
    form=UserLogin()
    if request.method=="POST":
        form=UserLogin(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            user=authenticate(username=username,password=password)
            login(request,user)
            if nexts:
                return redirect(nexts)
            messages.success(request,"successfully login")
            return redirect("todos:home")
            
            
    context={"form":form}
    return render(request,"accounts/login.html",context)

#custom signup method
def signup_user(request):
    nexts=request.GET.get("next")
    form=UserSignUp()
    if request.method=="POST":
        form=UserSignUp(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            password=form.cleaned_data.get("password")
            user.set_password(password)
            user.save()
            new_user=authenticate(username=user.username,password=password)
            login(request,new_user)
            if nexts:
                return redirect(nexts)
            return redirect("accounts:login")
    context={"form":form}
    return render(request,"accounts/signup.html",context)

#custom logout method
def logout_user(request):
    logout(request)
    return redirect("accounts:login")

todos/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Task
from . forms import TaskForm


#Home function adding show the detail of login clint
@login_required
def index(request):
    user=User.objects.get(username=request.user.username)
    user_task=user.task_set.all()
    if user_task:
        form=TaskForm()
        context={
            "form":form,
            "user_task":user_task
        }
        return render(request,"todos/index.html",context)
    else:
        form=TaskForm()
        context={"form":form}
        messages.info(request,"Please add some wish for today!!")
        return render(request,"todos/index.html",context)



#this function is use for adding todo Item       
@login_required
def add_todo(request):
    form=TaskForm()
    if request.method=="POST":
        form=TaskForm(request.POST)
        if form.is_valid():
            use=form.save(commit=False)
            use.user=request.user
            use.save()
            messages.success(request,"Successfully added a new item")
            return redirect("todos:home")
    else:
        context={"form":form}
        messages.info(request,"Please add some item into list")
        return render(request,"todos/index.html",context)

#this function is used for edit your item
@login_required
def edit(request,pk):
    tsk=get_object_or_404(Task,pk=pk)
    form=TaskForm(instance=tsk)
    if request.method=="POST":
        forms=TaskForm(request.POST,instance=tsk)
        if forms.is_valid():
            usr=forms.save(commit=False)
            usr.save()
            messages.success(request,"Successfully update your list")
            return redirect("todos:home")
    else:
        context={"form":form}
        messages.info(request,"This is a item which you try to update")
        return render(request,"todos/edits.html",context)



#This function is use for delete the item        
@login_required
def delete(request,pk):
    tsk=get_object_or_404(Task,pk=pk)
    tsk.delete()
    messages.success(request,"Successfully delete the item from your list")
    return redirect("todos:home")

#This function is use for complete the particular item
@login_required
def completes(request,pk):
     tsk=get_object_or_404(Task,pk=pk)
     tsk.complete=True
     tsk.save()
     messages.success(request,"Successfully compltete this item from your list")
     return redirect("todos:home")

#This function is use for delete thr complete item
@login_required
def compltete_one(request):
    Task.objects.filter(complete__exact=True).delete()
    messages.success(request,"Successfully delete all complete  item from your list")
    return redirect("todos:home")


#This function is used to delete all the item
@login_required
def delete_all(request):
    Task.objects.all().delete()
    messages.success(request,"Successfully delete all  item from your list")
    return redirect("todos:home")

accounts/templates/accounts/login.html
{%extends "todos/base.html"%}
{% load crispy_forms_tags %}

{%block title%}LOGIN{%endblock%}
{%block css%}
<style>
    body{
        background:#faeeee;
        font-family: 'Source Serif Pro';
}
.content{
    
    border:2px solid black;
    width:600px;
	margin: 20px auto;
	padding:20px;
	background-color: #fff;
	border-radius: 3px;
	box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75)
}
.inner{
    margin-left:20px;
    margin-top:20px;
}
input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

</style>
{%endblock%}
{%block body%}
   
<div class="container ">
    <div class="row justify-content-md-center">
        <div class="col col-md-6 col-sm-6 col-xs-6  content">
            
<form method="POST">{%csrf_token%}
   
    {{form|crispy}}
    <div class="row">
        <div class="inner">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
   
</form>

</div>
</div>
</div>

{%endblock%}

accounts/templates/accounts/signup.html
{%extends "todos/base.html"%}
{% load crispy_forms_tags %}

{%block title%}SIGNUP{%endblock%}
{%block css%}
<style>
    body{
        background:#faeeee;
        font-family: 'Source Serif Pro';
}
.content{
    border:2px solid black;
    width:600px;
	margin: 20px auto;
	padding:20px;
	background-color: #fff;
	border-radius: 3px;
	box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75)
    
}
.inner{
    margin-left:20px;
    margin-top:20px;
}
input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

</style>
{%endblock%}
{%block body%}

<div class="container">
<div class="row justify-content-md-center">
<div class="col col-md-6 col-sm-6 col-md-auto content">
    <h5>Signup</h5>
<form method="POST">{%csrf_token%}
    
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Submit</button>
       

    

</form>
</div>
</div>
</div>

{%endblock%}

todos/templates/todos/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{%static 'todos/index.css' %}">
    <title>{%block title%}{%endblock%}</title>
   {%block css%} {%endblock%}
  </head>
  {%include 'todos/navbar.html'%}
  <body>
    <div class="mt-5 pt-4">
      {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
      {% endif %}
      </div>
    {%block body%}
    
    
    {%endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

todos/templates/todos/edits.html
{%extends "todos/base.html"%}

{%block title%}HOME{%endblock%}
{%block css%} 
<style>
body{
		background-color: #638CB8;
	}
input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}
input::placeholder {
	  color: #d3d3d3;
	}
.submit{
		background-color: #6BA3E8;
	}
#content{
    width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75)
}


</style>
{%endblock%}

{%block body%}
    
<div class="container-fluid" id="wrapper">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4" id="content">
            <h6>WHAT DO YOU WANT TO DO TODAY?</h6>
                    <form method="POST" action=".">{%csrf_token%}
                        <div class="form-group">
                            <div class="input-group">
                                {{form.title}}
                                <input class="btn btn-info" type="submit" name="Create Task">
                            </div>
                        </div>
                        
                    </form>
                
            
                    
                        
						
						
						
					
        </div>
    </div>
</div>

{%endblock%}

todos/templates/todos/index.html
{%extends "todos/base.html"%}

{%block title%}HOME{%endblock%}
{%block css%}  
<style>
body{
	    background:#faeeee;
		font-family: 'Source Serif Pro',
	}
input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}
input::placeholder {
	  color: #d3d3d3;
	}
.submit{
		background-color: #6BA3E8;
	}
#content{
    width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75)
}
.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}
#todo-completed {
    
	text-decoration: line-through;
	background: rgba(149, 165, 166, .3);
}

</style>
{%endblock%}

{%block body%}
    
<div class="container-fluid" id="wrapper">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4" id="content">
            <h6>WHAT DO YOU WANT TO DO TODAY?</h6>
                    <form method="POST" action="{%url 'todos:add'%}">{%csrf_token%}
                        <div class="form-group">
                            <div class="input-group">
                                {{form.title}}
                                <input class="btn btn-info" type="submit" name="Create Task">
                            </div>
                        </div>
                        
                    </form>
                    <div class="row t10">
						<div class="col-lg-12">
							<div class="btn-toolbar">
								<div class="btn-group">
									<a href="{%url 'todos:completeone' %}"><button type="button" class="btn btn-danger">
										<i class="fa fa-trash-o" aria-hidden="true"></i> DELETE COMPLETED
									</button> </a>
								</div>
								<div class="btn-group ml-2">
                                    <a href="{%url 'todos:completedelete' %}"><button type="button" class="btn btn-danger">
										<i class="fa fa-trash-o" aria-hidden="true"></i> DELETE ALL
									</button></a>
								</div>
							</div>
						</div>
					</div>
            
                    
                        {%if user_task%}
                        {%for object in user_task%}
                        <div class="item-row">
                            <a class="btn btn-sm btn-info" href="{{object.get_absolute_url}}">Edit</a>
                            <a class="btn btn-sm btn-danger" href="{{object.delete_data}}">Delete</a>
                
                            {% if object.complete == True %}
                            <span id="todo-completed">{{object.title}}</span>
                            {% else %}
                            <span><a href="{%url 'todos:complete' object.pk%}">{{object.title}}</a></span>
                            {% endif %}
                        </div>
                        {%endfor%}
                        {%else%}
                        <p>Please add some data.</p>
                        {%endif%}
						
						
						
					
        </div>
    </div>
</div>

{%endblock%}

todos/templates/todos/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {%if request.user.is_authenticated%}
        <li class="nav-item ">
          <a class="nav-link" href="{%url 'todos:home'%}">Home</a>
        </li>
        
        <li class="nav-item ">
          <a class="nav-link" href="{%url 'accounts:logout'%}">Logout</a>
        </li>
        {%else%}
        <li class="nav-item ">
          <a class="nav-link" href="{%url 'accounts:login'%}">Login</a>
        </li>
        
        <li class="nav-item ">
          <a class="nav-link" href="{%url 'accounts:signup'%}">SignUP</a>
        </li>
      {%endif%}
       
      </ul>
     
    </div>
  </nav>